if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("useCometFocusedGlobeFilled16_viewer.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useCometFocusedGlobeFilled16_viewer",selections:[{alias:null,args:null,kind:"ScalarField",name:"globe_focus",storageKey:null}],type:"Viewer",abstractKey:null};e.exports=a}),null);
__d("CommunitySustainabilityActionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("265");c=b("FalcoLoggerInternal").create("community_sustainability_action",a);e.exports=c}),null);
__d("CommunitySustainabilityErrorFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("643");c=b("FalcoLoggerInternal").create("community_sustainability_error",a);e.exports=c}),null);
__d("CommunitySustainabilityLoggingUtils",["CommunitySustainabilityActionFalcoEvent","CommunitySustainabilityErrorFalcoEvent"],(function(a,b,c,d,e,f,g){"use strict";function a(a){c("CommunitySustainabilityActionFalcoEvent").log(function(){return babelHelpers["extends"]({},a,{product:"group_scoped_fundraisers",stack:"client"})})}function b(a){c("CommunitySustainabilityErrorFalcoEvent").log(function(){return babelHelpers["extends"]({},a,{product:"group_scoped_fundraisers"})})}function d(a){c("CommunitySustainabilityActionFalcoEvent").log(function(){return babelHelpers["extends"]({},a,{product:"shops",stack:"client"})})}function e(a){c("CommunitySustainabilityErrorFalcoEvent").log(function(){return babelHelpers["extends"]({},a,{product:"shops"})})}g.logFundraiserAction=a;g.logFundraiserException=b;g.logShopsAction=d;g.logShopsException=e}),98);
__d("CometComposerMediaAttachmentPendingMediaStates",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";a=b("$InternalEnum").Mirrored(["NEW","QUEUED","UPLOADING"]);c=a;f["default"]=c}),66);
__d("cometComposerValidateNoMediaCurrentlyUploading",["fbt","CometComposerMediaAttachmentPendingMediaStates"],(function(a,b,c,d,e,f,g,h){"use strict";function a(a){return(a.mediaAttachments||[]).some(function(a){return new Set(c("CometComposerMediaAttachmentPendingMediaStates").members()).has(a.state)})?h._("__JHASH__Oap1eBob0Br__JHASH__"):null}g["default"]=a}),98);
__d("EventCometComposerContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext({errorMetadata:null,isSaving:!1,mode:"create"});g["default"]=b}),98);
__d("CometBloodDonationAttachmentStrings",["fbt"],(function(a,b,c,d,e,f,g,h){"use strict";a=function(){return h._("__JHASH__lRwMTI3I4nB__JHASH__")};b=function(){return h._("__JHASH__4uK4Bu7Zzt3__JHASH__")};c=function(){return h._("__JHASH__z0nHm840dQg__JHASH__")};d=function(){return h._("__JHASH__KHQubmXIBKF__JHASH__")};e=function(a,b){return b==null?a:h._("__JHASH__h_ltaa03ooX__JHASH__",[h._param("Facility name (e.g. American Red Cross)",a),h._param("Category name (e.g. Blood Bank)",b)])};g.getScheduleCTA=a;g.getBookNowCTA=b;g.getBookAppointmentCTA=c;g.getAttachmentTitle=d;g.getFacilityNameWithCategory=e}),98);
__d("useCometFocusedGlobeFilled16",["ix","CometRelay","fbicon","recoverableViolation","useCometFocusedGlobeFilled16_viewer.graphql"],(function(a,b,c,d,e,f,g,h){"use strict";var i,j=i!==void 0?i:i=b("useCometFocusedGlobeFilled16_viewer.graphql");function a(a){a=d("CometRelay").useFragment(j,a);a=a==null?void 0:a.globe_focus;switch(a){case"ASIA":return d("fbicon")._(h("482014"),16);case"EAST":return d("fbicon")._(h("482028"),16);case"WEST":return d("fbicon")._(h("560119"),16);default:c("recoverableViolation")("Got a null or invalid globe focus type.","comet_ui");return d("fbicon")._(h("560119"),16)}}g["default"]=a}),98);
__d("CreateFundraiserClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1839");c=b("FalcoLoggerInternal").create("create_fundraiser_click",a);e.exports=c}),null);
__d("GivingClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("2018");c=b("FalcoLoggerInternal").create("giving_click",a);e.exports=c}),null);
__d("InviteUserDialogOpenFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1743706");c=b("FalcoLoggerInternal").create("invite_user_dialog_open",a);e.exports=c}),null);
__d("BloodDonationPartnerPrimaryBookingMethod",[],(function(a,b,c,d,e,f){a=Object.freeze({BOOKING_URL:"booking_url",PHONE:"phone"});f["default"]=a}),66);