if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("CometGamingVideoLiveViewerCountFetcherQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4884164861637141"}),null);
__d("CometGamingVideoLiveViewerCountFetcherQuery.graphql",["CometGamingVideoLiveViewerCountFetcherQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{defaultValue:null,kind:"LocalArgument",name:"broadcastIds"}],c=[{kind:"Variable",name:"ids",variableName:"broadcastIds"}],d={alias:null,args:null,kind:"ScalarField",name:"broadcast_status",storageKey:null},e={alias:null,args:null,kind:"ScalarField",name:"live_viewer_count_read_only",storageKey:null},f={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null};return{fragment:{argumentDefinitions:a,kind:"Fragment",metadata:null,name:"CometGamingVideoLiveViewerCountFetcherQuery",selections:[{alias:null,args:c,concreteType:"VideoBroadcastMultifetchEdge",kind:"LinkedField",name:"multifetch__VideoBroadcast",plural:!0,selections:[{alias:null,args:null,concreteType:"VideoBroadcast",kind:"LinkedField",name:"node",plural:!1,selections:[{alias:null,args:null,concreteType:"Video",kind:"LinkedField",name:"video",plural:!1,selections:[d,e],storageKey:null}],storageKey:null}],storageKey:null}],type:"Query",abstractKey:null},kind:"Request",operation:{argumentDefinitions:a,kind:"Operation",name:"CometGamingVideoLiveViewerCountFetcherQuery",selections:[{alias:null,args:c,concreteType:"VideoBroadcastMultifetchEdge",kind:"LinkedField",name:"multifetch__VideoBroadcast",plural:!0,selections:[{alias:null,args:null,concreteType:"VideoBroadcast",kind:"LinkedField",name:"node",plural:!1,selections:[{alias:null,args:null,concreteType:"Video",kind:"LinkedField",name:"video",plural:!1,selections:[d,e,f],storageKey:null},f],storageKey:null}],storageKey:null}]},params:{id:b("CometGamingVideoLiveViewerCountFetcherQuery_facebookRelayOperation"),metadata:{live:{config_id:"comet_gaming_live_viewer_count"}},name:"CometGamingVideoLiveViewerCountFetcherQuery",operationKind:"query",text:null}}}();e.exports=a}),null);
__d("CometGamingVideoLiveViewerCountFetcher.react",["CometGamingVideoLiveViewerCountFetcherQuery.graphql","CometRelay"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){a=a.broadcastIds;d("CometRelay").useLazyLoadQuery(h!==void 0?h:h=b("CometGamingVideoLiveViewerCountFetcherQuery.graphql"),{broadcastIds:a},{fetchPolicy:"store-and-network"})}g["default"]=a}),98);
__d("AdsLWISpecOverrideUtils",[],(function(a,b,c,d,e,f){"use strict";function a(a){return btoa(JSON.stringify(a))}f.encodeLWIClientSpecOverride=a}),66);
__d("CometAdPreferencesAdSettingsSectionQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4845613152182785"}),null);
__d("CometMarketplaceSellerAnnouncementCenterContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5156325217748820"}),null);
__d("CometMarketplaceYouAlertsContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5075906802518015"}),null);
__d("CometMarketplaceYouFollowingContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5631292450250187"}),null);
__d("CometMarketplaceYouPromotionsContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5156649557745303"}),null);
__d("CometMarketplaceYouPromotionsV2ContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8039316272808748"}),null);
__d("CometMarketplaceYouShippingOrdersFastContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="8387632554612674"}),null);
__d("GroupsCometAdminParticipationQuestionsContentQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6137428596285077"}),null);
__d("GroupsCometAdminParticipationQuestionsRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="4909973089079747"}),null);
__d("MarketplaceBoostedListingsContentContainerQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5306000902779585"}),null);
__d("MarketplaceCometRenewMultipleListingsDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="6986639071406121"}),null);