if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("DigitalCollectiblesGatingDigitalWalletSharingQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5300887709948884"}),null);
__d("DigitalCollectiblesGatingDigitalWalletSharingQuery$Parameters",["DigitalCollectiblesGatingDigitalWalletSharingQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("DigitalCollectiblesGatingDigitalWalletSharingQuery_facebookRelayOperation"),metadata:{},name:"DigitalCollectiblesGatingDigitalWalletSharingQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("NFTDigitalCollectiblesRootQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5417407228338599"}),null);
__d("NFTDigitalCollectiblesRootQuery$Parameters.facebook",["NFTDigitalCollectiblesRootQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("NFTDigitalCollectiblesRootQuery_facebookRelayOperation"),metadata:{live:{polling_interval:1e3}},name:"NFTDigitalCollectiblesRootQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("NFTDigitalCollectiblesRootQuery$Parameters",["cr:2425"],(function(a,b,c,d,e,f){"use strict";e.exports=b("cr:2425")}),null);
__d("NFTDigitalCollectiblesRootReTosCheckQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="5205128872948772"}),null);
__d("NFTDigitalCollectiblesRootReTosCheckQuery$Parameters.facebook",["NFTDigitalCollectiblesRootReTosCheckQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("NFTDigitalCollectiblesRootReTosCheckQuery_facebookRelayOperation"),metadata:{},name:"NFTDigitalCollectiblesRootReTosCheckQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("NFTDigitalCollectiblesRootReTosCheckQuery$Parameters",["cr:4806"],(function(a,b,c,d,e,f){"use strict";e.exports=b("cr:4806")}),null);
__d("NFTDigitalCollectiblesRoot.entrypoint",["DigitalCollectiblesGatingDigitalWalletSharingQuery$Parameters","JSResourceForInteraction","NFTDigitalCollectiblesRootQuery$Parameters","NFTDigitalCollectiblesRootReTosCheckQuery$Parameters"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(a){return{queries:{interopGatingQuery:{parameters:c("DigitalCollectiblesGatingDigitalWalletSharingQuery$Parameters"),variables:{}},query:{options:{fetchPolicy:"store-and-network"},parameters:c("NFTDigitalCollectiblesRootQuery$Parameters"),variables:{}},retosQuery:{parameters:c("NFTDigitalCollectiblesRootReTosCheckQuery$Parameters"),variables:{}}}}},root:c("JSResourceForInteraction")("NFTDigitalCollectiblesRoot.react").__setRef("NFTDigitalCollectiblesRoot.entrypoint")};g["default"]=a}),98);